-- Supabase schema for Maplewood Employee Compliance Tracker cloud sync
-- Tables
create extension if not exists "uuid-ossp";

create table if not exists public.employees (
  id uuid primary key default uuid_generate_v4(),
  payload jsonb not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.employee_requirements (
  id uuid primary key default uuid_generate_v4(),
  employee_id uuid not null references public.employees(id) on delete cascade,
  payload jsonb not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.imports (
  id uuid primary key default uuid_generate_v4(),
  status text not null check (status in ('pending', 'approved')),
  mode text not null default 'employees',
  file_name text,
  requested_by text,
  approved_by text,
  summary jsonb,
  mapping jsonb,
  header_row jsonb,
  row_count integer not null default 0,
  approved_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.import_rows (
  id bigint generated by default as identity primary key,
  import_id uuid not null references public.imports(id) on delete cascade,
  ordinal integer not null,
  raw jsonb,
  mapped jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

-- Updated at trigger
create or replace function public.touch_updated_at()
returns trigger as
$$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$ language plpgsql;

create trigger trg_employees_touch_updated
  before update on public.employees
  for each row execute function public.touch_updated_at();

create trigger trg_employee_requirements_touch_updated
  before update on public.employee_requirements
  for each row execute function public.touch_updated_at();

create trigger trg_imports_touch_updated
  before update on public.imports
  for each row execute function public.touch_updated_at();

-- Row level security
alter table public.employees enable row level security;
alter table public.employee_requirements enable row level security;
alter table public.imports enable row level security;
alter table public.import_rows enable row level security;

create policy "Allow anonymous reads" on public.employees
  for select using (true);
create policy "Allow anonymous reads" on public.employee_requirements
  for select using (true);
create policy "Allow anonymous reads" on public.imports
  for select using (true);
create policy "Allow anonymous reads" on public.import_rows
  for select using (true);

create policy "Service role writes" on public.employees
  for all using ((coalesce((auth.jwt() ->> 'role'), '') in ('service_role', 'admin')))
  with check ((coalesce((auth.jwt() ->> 'role'), '') in ('service_role', 'admin')));
create policy "Service role writes" on public.employee_requirements
  for all using ((coalesce((auth.jwt() ->> 'role'), '') in ('service_role', 'admin')))
  with check ((coalesce((auth.jwt() ->> 'role'), '') in ('service_role', 'admin')));
create policy "Service role writes" on public.imports
  for all using ((coalesce((auth.jwt() ->> 'role'), '') in ('service_role', 'admin')))
  with check ((coalesce((auth.jwt() ->> 'role'), '') in ('service_role', 'admin')));
create policy "Service role writes" on public.import_rows
  for all using ((coalesce((auth.jwt() ->> 'role'), '') in ('service_role', 'admin')))
  with check ((coalesce((auth.jwt() ->> 'role'), '') in ('service_role', 'admin')));

-- Approval routine merges mapped rows into employees table.
create or replace function public.approve_import(batch_id uuid, approved_by text)
returns jsonb as
$$
declare
  approved_at timestamptz := timezone('utc', now());
  pending_count integer := 0;
  inserted_employees jsonb := '[]'::jsonb;
  inserted_requirements jsonb := '[]'::jsonb;
  row_record record;
  mapped_payload jsonb;
  employee_id uuid;
  employee_requirements jsonb;
begin
  select count(*) into pending_count from public.imports where id = batch_id and status = 'pending';
  if pending_count = 0 then
    raise exception 'Import batch % not found or already approved.', batch_id;
  end if;

  update public.imports
    set status = 'approved',
        approved_at = approved_at,
        approved_by = coalesce(approved_by, requested_by),
        updated_at = approved_at
    where id = batch_id;

  for row_record in
    select mapped
    from public.import_rows
    where import_id = batch_id
    order by ordinal
  loop
    mapped_payload := coalesce(row_record.mapped, '{}'::jsonb);
    if not (mapped_payload ? 'id') then
      mapped_payload := jsonb_set(mapped_payload, '{id}', to_jsonb(uuid_generate_v4()));
    end if;
    if not (mapped_payload ? 'createdAt') then
      mapped_payload := jsonb_set(mapped_payload, '{createdAt}', to_jsonb(approved_at));
    end if;
    mapped_payload := jsonb_set(mapped_payload, '{updatedAt}', to_jsonb(approved_at), true);
    mapped_payload := jsonb_set(mapped_payload, '{status}', to_jsonb(coalesce(mapped_payload->>'status', 'Active')), true);

    employee_requirements := '[]'::jsonb;
    if mapped_payload ? 'employeeRequirements' then
      employee_requirements := mapped_payload->'employeeRequirements';
      mapped_payload := mapped_payload - 'employeeRequirements';
    end if;

    employee_id := (mapped_payload->>'id')::uuid;

    insert into public.employees (id, payload, created_at, updated_at)
    values (employee_id, mapped_payload, approved_at, approved_at)
    on conflict (id) do update
      set payload = excluded.payload,
          updated_at = approved_at;

    inserted_employees := inserted_employees || jsonb_build_array(mapped_payload);

    if jsonb_typeof(employee_requirements) = 'array' then
      for row_record in
        select jsonb_array_elements(employee_requirements) as item
      loop
        if not (row_record.item ? 'id') then
          row_record.item := jsonb_set(row_record.item, '{id}', to_jsonb(uuid_generate_v4()));
        end if;
        row_record.item := jsonb_set(row_record.item, '{employeeId}', to_jsonb(employee_id), true);
        row_record.item := jsonb_set(row_record.item, '{updatedAt}', to_jsonb(approved_at), true);
        insert into public.employee_requirements (id, employee_id, payload, created_at, updated_at)
        values (
          (row_record.item->>'id')::uuid,
          employee_id,
          row_record.item,
          approved_at,
          approved_at
        )
        on conflict (id) do update
          set payload = excluded.payload,
              updated_at = approved_at;
        inserted_requirements := inserted_requirements || jsonb_build_array(row_record.item);
      end loop;
    end if;
  end loop;

  return jsonb_build_object(
    'employees', inserted_employees,
    'employeeRequirements', inserted_requirements,
    'cursor', approved_at
  );
end;
$$ language plpgsql security definer set search_path = public;
